import { vueTpSaeClass } from "./class_tp_sae"
vueTpSaeClass.init({
    tableInfoAbonnement: document.querySelector("[id=table_info_abonnement]"),
    tableTotalAbonnement:document.querySelector("[id=table_total_abonnement]"),
    btnAbonnementDetail: document.querySelector("[id=btn_abonnement_detail]"),
    btnAbonnementAjouter: document.querySelector("[id=btn_abonnement_ajouter]"),
    btnAbonnementModifier: document.querySelector("[id=btn_abonnement_modifier]"),
    btnAbonnementSupprimer: document.querySelector("[id=btn_abonnement_supprimer]"),
    btnThemeValider:document.querySelector("[id=btn_theme_valider]"),
    btnThemeAnnuler:document.querySelector("[id=btn_theme_annuler]"),
    btnThemeModifer:document.querySelector("[id=btn_theme_modifier]"),
    btnThemeAjouter:document.querySelector("[id=btn_theme_btn_theme_ajouterannuler]"),
    btnAbonnementRetour: document.querySelector("[id=btn_abonnement_retour]"),
    btnAbonnementValider: document.querySelector("[id=btn_abonnement_valider]"),
    btnAbonnementAnnuler: document.querySelector("[id=btn_abonnement_annuler]"),
    divPageAbonnement: document.querySelector("[id=div_page_abonnement]"),
    divAbonnementTitre: document.querySelector("([id=div_abonnement_titre]"),
    edtIdentificationAdh: document.querySelector("[id=edt_identification_adh"),
    dateNumDate:document.querySelector("[id=date_num_date]"),
    edtNumAdh: document.querySelector("[id=edt_num_adh]"),
    edtTexteInvisible: document.querySelector("[id=edt_texte_invisible]"),
    textareaCommentaireAdh: document.querySelector("[id=textarea_commentaire_adh]"),
    divListeAbonnement: document.querySelector("[id=div_liste_abonnement]"),
    divInformationAdherent: document.querySelector("[id=div_information_adherent]"),
    divInformationAbonnement: document.querySelector("[id=div_information_abonnement]"),
    divNombreTotal: document.querySelector("[id=div_nombre_total]"),
    divSelectionThemes: document.querySelector("[id=div_selection_themes]"),
    selectThemes: document.querySelector("[id=select_themes]"),
    chkVersionPapier: document.querySelector("[id=chk_version_papier]"),
    chkModifierTheme: document.querySelector("[id=chk_modifier_theme]"),
    lblErreurIdendification: document.querySelector("[id=lbl_erreur_idendification]"),
    lblErreurAdh: document.querySelector("[id=lbl_erreur_ADH]"),
    lblErreurSelectionTheme: document.querySelector("[id=lbl_erreur_selectionTheme]"),
    lblErreurSelectThemes: document.querySelector("[id=lbl_erreur_select_themes]"),
})

